# Generated by Django 5.0 on 2024-02-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("username", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                (
                    "activity_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "activity_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("voice_channel_id", models.BigIntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "verbose_name_plural": "Member Activities",
                "ordering": ["-timestamp"],
            },
        ),
    ]
